# Generated by Django 3.1.4 on 2020-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("shorty", "0002_shorturl")]

    operations = [
        migrations.AlterField(
            model_name="shorturl",
            name="accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
